name: 'Config Entity Example'
type: module
description: 'Demonstrates how to create a config entity type.'
package: Example modules
core: 8.x
dependencies:
  - examples:examples

# Information added by Drupal.org packaging script on 2019-08-23
version: '8.x-1.0'
project: 'examples'
datestamp: 1566573495
