# Schema for the configuration files of the Menu per Role module.

menu_per_role.settings:
  type: config_object
  label: 'Menu per role settings'
  mapping:
    hide_show:
      type: integer
      label: 'Select what is shown when editing menu items.'
    hide_on_content:
      type: integer
      label: 'Show fields on menu items that point to content.'
